In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
raw_data_X = [
    [3.393533211, 2.331273381],
    [3.110073483, 1.781539638],
    [1.343808831, 3.368360954],
    [3.582294042, 4.679179110],
    [2.280362439, 2.866990263],
    [7.423436942, 4.696522875],
    [5.745051997, 3.533989803],
    [9.172168622, 2.511101045],
    [7.792783481, 3.424088941],
    [7.939820817, 0.791637231]
]  # 两列分别代表肿瘤的长和宽
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1] # 0是良性肿瘤，1是恶性肿瘤

In [4]:
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

In [5]:
x = np.array([8.093607318, 3.365731514])

In [6]:
%run kNN_function/kNN.py

In [8]:
predict_y = kNN_classify(6, X_train, y_train, x)
predict_y # 预测结果也前一节相同

1

# 使用scikit-learn中的kNN

In [9]:
from sklearn.neighbors import KNeighborsClassifier # 引入k近邻算法

In [10]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6) # 选取6个距离最近的点

In [11]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [13]:
kNN_classifier.predict(x) # 最好不要传入单个点(一维数组)，要传入多个元素组成的矩阵，如下

/Users/liangshanguang/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [14]:
X_predict = x.reshape(1, -1) # 行数是一行，列数为-1表示自适应。其实作用就是将待预测点x转换成2维矩阵

In [15]:
X_predict # 可以看到成为二维数组了

array([[ 8.09360732,  3.36573151]])

In [16]:
kNN_classifier.predict(X_predict)

array([1])

In [19]:
y_predict = kNN_classifier.predict(X_predict)
y_predict[0] # 取出第一个预测结果

1

# 封装成和sklearn一样模式的代码

In [26]:
%run kNN/kNN.py

In [27]:
knn_clf = kNNClassifier(k=6)
knn_clf.fit(X_train, y_train)

kNN(k = 6)

In [28]:
y_predict = knn_clf.predict(X_predict)

In [30]:
y_predict[0] # 返回正确结果

1