# 索引运算

In [3]:
import numpy as np

In [5]:
x = np.random.normal(0, 1, size=1000000)  # 产生100万个均值为0，标准差为1的随机数

In [7]:
np.min(x)  # 最小的元素

-4.6195198842216749

In [9]:
np.argmin(x) # 最小元素对应的下标

544389

In [12]:
x[544389] # 验证上面两个的结论

-4.6195198842216749

In [14]:
np.argmax(x) # x中最大元素对应的下标

27149

In [16]:
x[27149] 

5.2454257417993624

In [18]:
np.max(x) # 验证上面两个单元格的结论

5.2454257417993624

# 排序和使用索引

In [20]:
x = np.arange(16) # [0, 16)按步长为1取值。起点0和步长1都是默认值

In [22]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
np.random.shuffle(x) # 对x进行乱序处理
x

array([ 9,  4, 12,  5,  2,  8,  1,  0,  6,  7, 14, 10, 11, 13, 15,  3])

In [27]:
np.sort(x) # 返回一个排好序的对象，但是没有改变向量本身

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
x # 验证下上面的结论

array([ 9,  4, 12,  5,  2,  8,  1,  0,  6,  7, 14, 10, 11, 13, 15,  3])

In [32]:
x.sort()  # 直接用x的sort方法，就可以修改x了

In [34]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
X = np.random.randint(10, size=(4, 4)) # 产生范围为[0, 10)的随机数，组成4*4的矩阵

In [38]:
X

array([[3, 0, 4, 5],
       [5, 6, 0, 9],
       [1, 3, 8, 1],
       [7, 4, 0, 0]])

In [40]:
np.sort(X) # 对矩阵排序实际是对每一行排序(默认有个axis参数 = 1)

array([[0, 3, 4, 5],
       [0, 5, 6, 9],
       [1, 1, 3, 8],
       [0, 0, 4, 7]])

In [44]:
np.sort(X, axis=0)  # = 0 表示沿着列排序

array([[1, 0, 0, 0],
       [3, 3, 0, 1],
       [5, 4, 4, 5],
       [7, 6, 8, 9]])

In [47]:
np.sort(X, axis=1)  # = 1 表示沿着行排序，默认就是沿着行排序

array([[0, 3, 4, 5],
       [0, 5, 6, 9],
       [1, 1, 3, 8],
       [0, 0, 4, 7]])

In [49]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
np.random.shuffle(x) # 随机打乱

In [55]:
x

array([11, 14,  1,  3,  4,  6,  2, 15,  7, 13,  5, 12,  0,  9,  8, 10])

In [57]:
np.argsort(x)  # 把数组排好序，显示地一次是最小值的下标、次小值的下表.....次大值的下标、最大值的下标

array([12,  2,  6,  3,  4, 10,  5,  8, 14, 13, 15,  0, 11,  9,  1,  7])

In [62]:
np.partition(x, 3) # 类似归并排序中的partition，把大于3的值放在右边，小于3的值放在左边。但左右两侧并不是有序地

array([ 0,  1,  2,  3,  4,  5, 10,  8,  7,  9,  6, 11, 12, 13, 14, 15])

In [63]:
np.argpartition(x, 3) # 类似归并排序中的partition，把大于3的值的下标(也可称为索引)放在右边，小于3的值放在左边。但左右两侧并不是有序地

array([12,  2,  6,  3,  4, 10, 15, 14,  8, 13,  5,  0, 11,  9,  1,  7])

In [67]:
np.argsort(X, axis=1) # 按照行进行排序，显示地是对应元素的下表(也称索引),横着看，第一行第一列是最小元素下标是1，第一行第二列是次小元素下标是0....

array([[1, 0, 2, 3],
       [2, 0, 1, 3],
       [0, 3, 1, 2],
       [2, 3, 1, 0]])

In [68]:
X  

array([[3, 0, 4, 5],
       [5, 6, 0, 9],
       [1, 3, 8, 1],
       [7, 4, 0, 0]])

In [70]:
np.argsort(X, axis=0) # 按照列进行排序，显示地是对应元素的下表(也称索引),竖着看，第一列第一行是最小元素下标是1，第一列第2行是次小元素下标是0....

array([[2, 0, 1, 3],
       [0, 2, 3, 2],
       [1, 3, 0, 0],
       [3, 1, 2, 1]])

In [72]:
np.argpartition(X, 2, axis = 1) # 看第一行，小于2的元素的下标在左边，大于等于2的元素的下标在右边....依次类推

array([[1, 0, 2, 3],
       [2, 0, 1, 3],
       [0, 3, 1, 2],
       [2, 3, 1, 0]])

In [73]:
np.argpartition(X, 2, axis = 0) # 看第一列，小于2的元素的下标在上边，大于2的元素的下标在下边....依次类推

array([[2, 0, 1, 3],
       [0, 2, 3, 2],
       [1, 3, 0, 0],
       [3, 1, 2, 1]])