# 测试我们自己的算法

In [8]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [9]:
# 鸢尾花数据样本
iris = datasets.load_iris()

In [10]:
X = iris.data
y = iris.target

In [11]:
X.shape

(150, 4)

In [12]:
y.shape

(150,)

# train_test_split  训练和测试数据分离,大部分用来训练，一小部分用来验证

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
# 直接对X和y进行shuffle会导致X和y不再同步。既然X和y的行数是一样的，那么更妙的解决方案第对索引进行shuffle
shuffle_indexes = np.random.permutation(len(X)) # 元素个数来作为随机索引的个数

In [16]:
shuffle_indexes

array([104,  75,  29, 124,  85,  12, 133, 115,  56,   4,  38,  60,  51,
        66,  21,   9, 100,  55,  44,  47,  92,  96, 117, 109, 142, 129,
       145, 108,   7, 120,  25,  50,   1,  88, 134,  15,  28, 125,   2,
         6,  42,  69,  45,  64,  58,  11,  48, 140,  68, 126,  22, 127,
        36,  78,  81,  71, 106, 118,  70,  43, 131,  72, 148,   8,  46,
         5,  62,  79, 111,  16, 128,  84,  26,  53,  83,  20,  17,  89,
        13,  35, 144, 138, 139, 122, 103, 107,  97,  10, 121, 123,  67,
        94,  18,  95,  24,  39,  34,  61, 149, 112,  33,  37,  41, 135,
       116,  77,  93,  63, 102,  82, 110, 146,  91,  57,  32, 119,  99,
        31,  23,  98,  27,  54,  86, 114,   3, 136, 132,  49, 147,  14,
        19, 101,   0,  80,  76,  65,  90, 141, 105, 113,  40,  52,  73,
       143, 137,  59,  30,  74,  87, 130])

In [19]:
test_ratio = 0.2  # 选取多大比例的数据进行模型验证
test_size = int(len(X)*test_ratio)

In [20]:
test_size

30

In [25]:
test_indexes = shuffle_indexes[:test_size] # 取样本数据的前test_size个作为测试数据集
train_indexes = shuffle_indexes[test_size:] # test_size后面的数据作为训练数据集

In [26]:
test_indexes

array([104,  75,  29, 124,  85,  12, 133, 115,  56,   4,  38,  60,  51,
        66,  21,   9, 100,  55,  44,  47,  92,  96, 117, 109, 142, 129,
       145, 108,   7, 120])

In [28]:
train_indexes

array([ 25,  50,   1,  88, 134,  15,  28, 125,   2,   6,  42,  69,  45,
        64,  58,  11,  48, 140,  68, 126,  22, 127,  36,  78,  81,  71,
       106, 118,  70,  43, 131,  72, 148,   8,  46,   5,  62,  79, 111,
        16, 128,  84,  26,  53,  83,  20,  17,  89,  13,  35, 144, 138,
       139, 122, 103, 107,  97,  10, 121, 123,  67,  94,  18,  95,  24,
        39,  34,  61, 149, 112,  33,  37,  41, 135, 116,  77,  93,  63,
       102,  82, 110, 146,  91,  57,  32, 119,  99,  31,  23,  98,  27,
        54,  86, 114,   3, 136, 132,  49, 147,  14,  19, 101,   0,  80,
        76,  65,  90, 141, 105, 113,  40,  52,  73, 143, 137,  59,  30,
        74,  87, 130])

In [29]:
# Fancy_indexes 获取训练数据集
X_train = X[train_indexes]
y_train = y[train_indexes]
# Fancy_indexes 获取测试数据集
X_test = X[test_indexes]
y_test = y[test_indexes]

In [30]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [31]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


# 使用我们自定义的算法

In [61]:
from playML.model_selection import train_test_split

In [62]:
X_train, y_train, X_test, y_test = train_test_split(X, y)

In [63]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [64]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [65]:
from playML.kNN import kNNClassifier

In [66]:
my_knn_clf = kNNClassifier(k=3)

In [67]:
my_knn_clf.fit(X_train, y_train)

kNN(k = 3)

In [68]:
y_predict = my_knn_clf.predict(X_test)

In [69]:
y_predict # 预测结果

array([0, 1, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 2, 2, 2, 0, 0, 1, 0, 2, 2, 1,
       1, 1, 2, 1, 1, 2, 2])

In [70]:
y_test   # 实际结果

array([0, 2, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 0, 2, 2, 2, 0, 0, 1, 0, 2, 2, 1,
       1, 1, 2, 1, 1, 2, 2])

In [71]:
sum(y_predict == y_test)  # 看看两个数组中中多少相同地，也即预测正确的

29

In [72]:
sum(y_predict == y_test)/len(y_test) # 获得正确率.结果其实是和前面选取的随机数组有关地

0.96666666666666667

# sklearn中的train_test_split

In [73]:
from sklearn.model_selection import train_test_split

In [79]:
# 注意 X_train, X_test, y_train, y_test的序列和上面的不同哈。要想设置随机种子，传入random_state参数即可
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 这里的test_size就相当于上面的test_ratio

In [80]:
print(X_train.shape)
print(y_train.shape)

(105, 4)
(105,)


In [81]:
print(X_test.shape)
print(y_test.shape)

(45, 4)
(45,)
